ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
RUN set -xe && \
    apk add --no-cache --purge -uU supervisor inotify-tools && \
	rm -rf /var/cache/apk/* /tmp/*
#
ENTRYPOINT ["supervisord"]
CMD ["--nodaemon", "--configuration", "/etc/supervisord.conf"]
# ENTRYPOINT ["/bin/bash"]
